### ISSUE TITLE
login url是啥

### ISSUE THREAD

**Issue by kevinmay99** [ZimoLoveShuang/auto-submit#2]
教务系统爬虫404了

**Comment by ZimoLoveShuang** [comment]
教务系统爬虫涉及收费接口，已经闭源。login_url是借助上一个教务系统爬虫开放出来的API，用作模拟登录真正的教务系统获取cookie使用，因为已经写过一次，所以我并不想在这个脚本里面在写一次模拟登录，就是这样



---原始邮件---
发件人: "kevinmay99"<notifications@github.com&gt;
发送时间: 2020年4月4日(周六) 晚上10:45
收件人: "ZimoLoveShuang/auto-submit"<auto-submit@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ZimoLoveShuang/auto-submit] login url是啥 (#2)




 
教务系统爬虫404了

**Comment by kevinmay99** [comment]
大佬能私发一下让我研究研究吗，卡在登录那一步了。
如果可以的话，这是我的邮箱:xtgcpone@gmail.com

**Comment by ZimoLoveShuang** [comment]
登录是用Java写的，其实很简单，1.拿到登录的参数（去登录页面找，里面有很多隐藏的input，有的学校还有一定的加密），2.检查验证码，3.识别验证码，4.提交，获取cookie就可以了



发自我的小米手机在 kevinmay99 <notifications@github.com>，2020年4月5日 14:04写道：

大佬能私发一下让我研究研究吗，卡在登录那一步了。

如果可以的话，这是我的邮箱:xtgcpone@gmail.com



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ZimoLoveShuang/auto-submit/issues/2#issuecomment-609364415",

"url": "https://github.com/ZimoLoveShuang/auto-submit/issues/2#issuecomment-609364415",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ZimoLoveShuang** [comment]
solve
